### ISSUE TITLE
chimera and pegazus

### ISSUE THREAD

**Issue by bartekGardas** [euro-hpc-pl/SpinGlassPEPS.jl#13]
Before addressing Krzysiek's ideas, I think we need to write a couple of od aux functions similar to those known from the D-Wave repo, https://docs.ocean.dwavesys.com/projects/dwave-networkx/en/latest/_modules/dwave_networkx/generators/chimera.html

Thank include generating chimer/pegasus instances, changing coordinate systems, etc.

TODO:

- [x] Chimera graph
- [ ] Pegasus graph

**Comment by lpawela** [comment]
This is now outdated, closing
