### ISSUE TITLE
Chimera graph in graph.jl

### ISSUE THREAD

**Issue by kdomino** [euro-hpc-pl/SpinGlassPEPS.jl#16]
1. Is outer_connections(c::Chimera, src, dst)  symmetric in the sense of the order of output edges:
outer_connections(c::Chimera, v1, v2 ) = ? outer_connections(c::Chimera, v2, v1) 
This is crucial to ensure that bonding spins fit between peps elements. 

2. Can one make a similar structure for a grid (last clusters may be smaller), and for chimera with grater unit cell e.g. c(1,2); c(2,1), c(2,2), ....

**Comment by bartekGardas** [comment]
1. outer_connections is "experimental". Try using filter_edges(c.graph, :outer, (v, w)) to get all edges between clusters v and w. I think that the tags Lukasz implemented are symmetric and I not sure if we change that. You can always use unique_neighbors(node) to get "upper triangular" elements.

2. Generally, the ideas behind tagging is precisely not to build such structures, but rather filter edges and vertices having specific properties. One thing we should add to the Chimer struct though is the factor graph. In the factor, graph nodes could represent, in particular, larger chimera's cells. I think this would be the cleanest way to do that.

**Comment by kdomino** [comment]
OK, I see

**Comment by kdomino** [comment]
So It will be just a step between Ising graph and factor graph, I will think about it then

**Comment by kdomino** [comment]
For larger chimera cell we will need to remove some of outer connections and merge clusters

**Comment by bartekGardas** [comment]
The idea here is to call factor_graph with some parameters on the Chimera structure to induce the desired grid structure. All necessary information should there, including low energy spectrum, energies between bonds, etc. From this, building peps tensors should be easy and flexible.

**Comment by kdomino** [comment]
I will implement the low energy spectrum on the implementation I have, and then, think how to merge with yours clustering.

**Comment by kdomino** [comment]
There is still however some problem I am afraid, as you want to make it to simple, I can not merge it now.
