### ISSUE TITLE
Gibbs to MPO

### ISSUE THREAD

**Issue by bartekGardas** [euro-hpc-pl/SpinGlassPEPS.jl#4]
Can we write a function that takes the adjacency matrix for the Ising model (or just the instance, ie., dict)) and returns pairs of disjoint edges? The idea here is to pack as many Boltzmman factors as possible into one MPO of dimension D=2.

**Comment by lpawela** [comment]
What do you mean by "pairs of disjoint edges"?

**Comment by bartekGardas** [comment]
For instance, on a grid 3x3 one such set would be {(1,2), (4,5), (7,8), (6,9)}. These pairs do not share a common node and thus can contribute to a single MPO of bond dim 2.

**Comment by lpawela** [comment]
I still don't see how we have PAIRS of edges here.

**Comment by bartekGardas** [comment]
Not pairs, my bad! I meant disjoint edges as in the example given above.

**Comment by bartekGardas** [comment]
Now that I think about, we will need disjoint stripes...
