### ISSUE TITLE
factor_graph(m::Int, n::Int, hdir::Symbol=:LR, vdir::Symbol=:BT)

### ISSUE THREAD

**Issue by kdomino** [euro-hpc-pl/SpinGlassPEPS.jl#41]
Is it possible to have a key (or at least function) determining the row and the column of the PEPS lattice corresponding to the node of the factor graph.

**Comment by bartekGardas** [comment]
There is a new branch (called gowina), which incorporates a different strategy, in particular introduces structures like NetworkGraph, PepsGraph that store all the necessary information.

**Comment by bartekGardas** [comment]
In particular, the very functionality you are asking for is realized via: MPO(peps, i), see PEPS.jl
