### ISSUE TITLE
update Manifest.toml

### ISSUE THREAD

**Issue by kdomino** [euro-hpc-pl/SpinGlassPEPS.jl#43]
I need to add StatsBase.jl however I do not know how to update Manifest.toml automatically

**Comment by lpawela** [comment]
`Manifest.toml` should not be committed to the repo, dependencies are defined in `Project.toml`.

**Comment by kdomino** [comment]
so explain me this:

ERROR: `StatsBase` is a direct dependency, but does not appear in the manifest. If you intend `StatsBase` to be a direct dependency, run `Pkg.resolve()` to populate the manifest. Otherwise, remove `StatsBase` with `Pkg.rm("StatsBase")`. Finally, run `Pkg.instantiate()` again.
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:52

**Comment by lpawela** [comment]
Just follow the instructions - `resolve` should fix it.

**Comment by kdomino** [comment]
(@v1.5) pkg> resolve
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`

**Comment by lpawela** [comment]
Is `StatsBase` present in `Project.toml`?

**Comment by kdomino** [comment]
It is:

https://github.com/iitis/SpinGlassPEPS.jl/blob/kd_graphic/Project.toml

**Comment by lpawela** [comment]
You don't have `StatsBase` added. Do `]add StatsBase`.

**Comment by kdomino** [comment]
no change
