### ISSUE TITLE
projectors set a wrong index value

### ISSUE THREAD

**Issue by kdomino** [euro-hpc-pl/SpinGlassPEPS.jl#50]
In:
https://github.com/iitis/SpinGlassPEPS.jl/tree/kd/indexing-tests/benchmarks

a simple example of solving 3 spin problem is made in indexing_example.jl
These spins are structured in two tensors. First step is to calculate first two spins from the first tensor. It works fine.
The second is to select the correct slice of the second tensor and compute spins from it. There one need to take o solution of the first tensor and use it to select the right row of the projector. Then the result vector need to be contracted with the second tensor. This does not work in the example, as a wrong slice of the second tensor is selected. There is something wrone either in the projector or some intermediate re-indexing step is necessary

**Comment by kdomino** [comment]
Further if you chose spectrum = full_spectrum in a factor graph projectors gives always the lexicographic order what looks odd:
full spectrum projs
4×2 Array{Float64,2}:
 1.0  0.0
 1.0  0.0
 0.0  1.0
 0.0  1.0

**Comment by kdomino** [comment]
I have added examples in 
https://github.com/iitis/SpinGlassPEPS.jl/tree/kd/indexing-tests/benchmarks
where the index setting does not work. Most probably either tensors are not correctly constructed or there are problems with projectors.

**Comment by lpawela** [comment]
@kdomino why am I assigned to this? I thought we agreed that @annamariadziubyna will look into this issue.

Also the example should provide a minimal code example to reproduce the problem. Are 700 lines of code necessary to reproduce the issue?

**Comment by kdomino** [comment]
@lpawela 

ask @bartekGardas

**Comment by bartekGardas** [comment]
Can we cook up a bit simpler example (such that @lpawela can be incorporated at this stage), 10-20 lines where things go wrong? Anyway, 700 lines of code is a bite excessive.

**Comment by kdomino** [comment]
The simple example where the solution of the brute force differs from the solution of peps are in:

benchmarks/indexing_example_short.jl

**Comment by annamariadziubyna** [comment]
I computed the tensors by hand. If we take into account the interaction between spin 2-3 in the first tensor A1, then the tensors in the tests are well built, in particular A2 is diagonal. And the problem is with something else that I cannot see yet.

**Comment by bartekGardas** [comment]
Could you please add those explicit tensor to a new example? I would be nice to have such an example. The problem may be with rank, we are inspecting it now ...

**Comment by kdomino** [comment]
done in benchmarks/indexing_example_short.jl

**Comment by bartekGardas** [comment]
Let's merge lp/origin/rank-fix, and see if the problems persist.

**Comment by kdomino** [comment]
It look ok now

**Comment by bartekGardas** [comment]
Great! Indeed, it seems to be working.... Is this a patch or a permanent solution? Is safe to merge your branch? Could you please explain in 2-3 sentences what the problem was?

**Comment by kdomino** [comment]
The first problem was the fact that the energy of interaction between clusters were included in left (not right) tensor of the PepsRow. There setting of indices was not possible. Second problem was more fundamental as with low beta tracing off the some spins not always lead to the right solution. An example is included in indexing_example_short.jl. Beside this I am running random tests, it they pass we will have the permanent solution ready to be merged to master.
