### ISSUE TITLE
I do not know how to use PEPSrow

### ISSUE THREAD

**Issue by kdomino** [euro-hpc-pl/SpinGlassPEPS.jl#55]
g1 = make_interactions_case2() is the ising graph of the 4x4 grid:

Code:
g1 = make_interactions_case2()

    m = 2
    n = 2
    t = 4

    update_cells!(
      g1,
      rule = square_lattice((m, 1, n, 1, t)),
    )

    fg = factor_graph(
        g1,
        16,
        energy=energy,
        spectrum=brute_force,
    )

    origin = :NW
    x, y = m, n

    peps = PepsNetwork(x, y, fg, β, origin)

returns:

Got exception outside of a @test
  Error: 2 < 3
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] NetworkGraph(::MetaDiGraph{Int64,Float64}, ::Dict{Any,Any}, ::Float64) at /home/kdomino/.julia/dev/SpinGlassPEPS/src/PEPS.jl:19
   [3] PepsNetwork(::Int64, ::Int64, ::MetaDiGraph{Int64,Float64}, ::Float64, ::Symbol) at /home/kdomino/.julia/dev/SpinGlassPEPS/src/PEPS.jl:80
   [4] macro expansion at /home/kdomino/.julia/dev/SpinGlassPEPS/test/peps_tests.jl:486 [inlined]
   [5] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
   [6] top-level scope at /home/kdomino/.julia/dev/SpinGlassPEPS/test/peps_tests.jl:442
   [7] include(::String) at ./client.jl:457
   [8] top-level scope at /home/kdomino/.julia/dev/SpinGlassPEPS/test/runtests.jl:53
   [9] include(::String) at ./client.jl:457
   [10] top-level scope at none:6
   [11] eval(::Module, ::Any) at ./boot.jl:331
   [12] exec_options(::Base.JLOptions) at ./client.jl:272
   [13] _start() at ./client.jl:506

**Comment by bartekGardas** [comment]
I think that your construction is OK, the error you are seeing tells you, in particular, that the factor graph has only 3 edges (and it should have 4). Anyways, I tried to run it on `16_001.txt` instance, and it works just fine. Hence, the error is somewhere in the instance itself, which you generate as `g1 = make_interactions_case2()`.  

Couple of remarks: 
1. The example file where the error occurs is massive, and thus hard to debug. We should avoid, in particular, multiply tests per @settest. 
2. Problems with instances clearly shows that we need to visualize graphs. For instance, now, I cannot tell what is the key difference between `make_interactions_case2()`, which does not work, and `16_001.txt`, which does.

**Comment by kdomino** [comment]
can you change an order of elements in 16_001.txt

**Comment by bartekGardas** [comment]
You can change it, yes, but it already has a correct convention (i < j).

**Comment by kdomino** [comment]
Will it work, btw. 16_001.txt is not a greed, the 4x4 greed should have 16 + 3*4 +3*4 = 40 elements

**Comment by kdomino** [comment]
so  (i < j) is required?

**Comment by kdomino** [comment]
16 + 3x4 +3x4 = 40

**Comment by bartekGardas** [comment]
1) It should not be. 2) some edges may be missing.

**Comment by kdomino** [comment]
ok, I see it is by purpose

**Comment by kdomino** [comment]
I changed make_interactions_case2() it looks like 16_001.txt but with all connections. Will the factor graph work now

**Comment by kdomino** [comment]
I checked on the paper, it is a grid

**Comment by bartekGardas** [comment]
It should, so does it?

**Comment by kdomino** [comment]
at the beginning of peps_tests.jl I made the test set "factor graph and peps formation". The factor graph has wrong number of edges for both above-mentioned instances

**Comment by kdomino** [comment]
it is probably the case of numeration, 
udpate_cells!() requires following:

1 -- 2 -- . -- 5 -- 6
|        |   .    |       |
3 -- 4 -- . -- 7 -- 8
|       |   .    |       |
.........................................
9 -- 10 -- . -- 13 -- 14
|       |     .      |       |
11--12-- .-- 15 -- 16

and will not comply with the collunwise:

.
1 -- 2 -- . -- 3 -- 4
|      |     .     |      |
5 -- 6 -- . -- 7 -- 8
|      |     .     |      |
.........................................
9 --10 -- . --11 --12
|      |      .    |       |
13--14-- .--15 --16

perhaps it will be beneficial to have the udpate_cells2!() to copy with the collumn-wise (or row-wise) notation.
This will improve generality and allow to compare solutions with various cell size (without changing the instance)

**Comment by bartekGardas** [comment]
This is a problem with the convention for indexing. The pathological instance has the default one.

**Comment by bartekGardas** [comment]
![IMG_0046](https://user-images.githubusercontent.com/40250837/106281382-73c9d180-623f-11eb-914c-50e49712f9f8.jpg)

**Comment by bartekGardas** [comment]
My understanding is that @kdomino has many hand-crafted examples, which use different enumeration. At this point, the easiest way is just to transform them to the NW notation.

**Comment by annamariadziubyna** [comment]
By the way, in this pathological instance, bond dimension between second and third cluster should be 8, not 4. I checked it but I didn't change the picture.

**Comment by bartekGardas** [comment]
The aforementioned convention is codded in lattice.jl, in `square_lattice`, to be more specific. There is no problem to have many enumerations. If you have the need for different ordering, please add the corresponding function to that file.

**Comment by kdomino** [comment]
I put yours (pathological) numeration to tests as make_interactions_case3() -- it works there. So the issue is as it stands.

**Comment by bartekGardas** [comment]
Great! Good to have an  independent confirmation. Note also that when `t=1` (trivial clusters) in your example, everything works as well since in this case your enumeration agrees with `square_lattice`.

**Comment by bartekGardas** [comment]
It seems to me that `square_lattice((2, 2, 2, 2, 1))` should give you exactly what you want. The tuple `(m, um, n, un, t) = (2, 2, 2, 2, 1)` tells the `square_lattice` function to build an `m x n` grid of  clusters (having `t=1` elements), and then to groups thereof into `um x un` sub-grids.

**Comment by kdomino** [comment]
Solved by using square_lattice() or particular rule encoded in Dict.
