### ISSUE TITLE
implementation of the new probability computation function

### ISSUE THREAD

**Issue by kdomino** [euro-hpc-pl/SpinGlassPEPS.jl#57]
I attempted to implement new probability computation function.

conditional_probabs(peps::PepsNetwork, ps::Partial_sol{T}, boundary_mps::MPS{T}, peps_row::PEPSRow{T}) where T <: Real

 It is in peps_no_type.jl (refactoring branch) from line function 299

Test are in testing_probabilities.jl. on the 4 (multi spins) node grid. Results from first row are roughly ok, but from second are not (node 3 and 4). I have displayed tensor 3 and 4 there, and there appears to much zeros in my opinion. E.g. tensor 4 as composed of two interaction matrices should have no zero element but it has 4 (out of 8). So perhaps projectors / coupling are i wrong order in the vertical direction. 

Further I may have done some mistake in the conditional_probabs but i could not find it. I would be glad for any assistance. 
Thanks

**Comment by bartekGardas** [comment]
The issue is because trivial MPOs are not included in conditional_probabs. I will try to fix this.

**Comment by kdomino** [comment]
It appears to be solved
