### ISSUE TITLE
@memoize

### ISSUE THREAD

**Issue by bartekGardas** [euro-hpc-pl/SpinGlassPEPS.jl#65]
I believe it would be elegant and efficient to have all environments "memoized".  This should simplify, in particular, `_right_sweep_var!!`, `_left_sweep_var!!` and thus `compress` as a result.

**Comment by lpawela** [comment]
This requires careful profiling. If it is beneficial than we will add it.

**Comment by bartekGardas** [comment]
Sure thing. Note, those functions are already cached, but by hand. The idea is to do this automatically using @memoize.
