### ISSUE TITLE
svd, qr questions

### ISSUE THREAD

**Issue by bartekGardas** [euro-hpc-pl/SpinGlassPEPS.jl#69]
1. Does the partial svd we are using normalizes singular values? If so, how? 
2. What is the phase of U, and V on the last site? I was under the impression that is always the same (+1 or -1). Is that really the case?

**Comment by lpawela** [comment]
1. It does not. The algorithm is probabilistic hence the calculated singular values can change from one run to another. The found singular values are not normalized.
2. It is not document anywhere, but experiments suggest that the phase is fixes to 1 in this case.
